export const blankBingo = {
  type: "QUINA",
  pieces: {
    0: { number: "", isMarked: false },
    1: { number: "", isMarked: false },
    2: { number: "", isMarked: false },
    3: { number: "", isMarked: false },
    4: { number: "", isMarked: false },
    5: { number: "", isMarked: false },
    6: { number: "", isMarked: false },
    7: { number: "", isMarked: false },
    8: { number: "", isMarked: false },
    9: { number: "", isMarked: false },
    10: { number: "", isMarked: false },
    11: { number: "", isMarked: false },
    12: { number: "", isMarked: false },
    13: { number: "", isMarked: false },
    14: { number: "", isMarked: false },
    15: { number: "", isMarked: false },
    16: { number: "", isMarked: false },
    17: { number: "", isMarked: false },
    18: { number: "", isMarked: false },
    19: { number: "", isMarked: false },
    20: { number: "", isMarked: false },
    21: { number: "", isMarked: false },
    22: { number: "", isMarked: false },
    23: { number: "", isMarked: false },
    24: { number: "", isMarked: false },
  },
};
